
import analyzers.LexicalAnalyzer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author clases
 */
public class Lexico extends javax.swing.JFrame {
    String texto;
    /**
     * Creates new form Lexico
     */
    public Lexico(String text) {
        texto = text; 
        initComponents();
	SinErrores.setVisible(false);
        /* 
        Database db = new Database();
        HashMap<String, ? extends Object> db_map = (HashMap) db.getMap();
        LexicalAnalyzer lx = new LexicalAnalyzer(db_map);
        String salida = lx.getOneLine(main.Entrada.getText().replaceAll(" ", ""));
        HashMap<String, HashMap> analisis_lexico = lx.analisys(text);
        System.out.println(analisis_lexico);
        
        ArrayList<String> letters = appendToArray("Letra", analisis_lexico);
        ArrayList<String> numbers = appendToArray("Numero", analisis_lexico);
        */
        
        Database db = new Database();
        HashMap<String, ? extends Object> db_map = (HashMap) db.getMap();
        LexicalAnalyzer lx = new LexicalAnalyzer(db_map);
        HashMap<String, HashMap> analisis_lexico = lx.analisys(text);
        String salida = lx.getOneLine(main.Entrada.getText().replaceAll(" ", ""));
        
        CantidadEspacios.setText("Cantidad de Espacios: "+LexicalAnalyzer.countSpaces(text));
        
        
        
        Pantalla.setText(salida);
        
        Analisis(analisis_lexico,"Letra",letras,CantidadLetras);
        Analisis(analisis_lexico,"Numero",Numeros,CantidadNumeros);
        Analisis(analisis_lexico,"Operador",Operadores,CantidadOperadores);
        Analisis(analisis_lexico,"Separador",Separadores,CantidadSeparadores);
        Analisis(analisis_lexico,"Especial",Especiales,CantidadEspeciales);
        Analisis(analisis_lexico,"Error",Errores,CantidadErrores);
        
        if (Errores.getItemCount()==0){
            Sintatico.setEnabled(true);
            main.sintactico.setEnabled(true);
	    SinErrores.setVisible(true);
	    Errores.setVisible(false);
        }else{
            Sintatico.setEnabled(false);
            main.sintactico.setEnabled(false);
        }
    }
    
    public void Analisis (HashMap<String, HashMap> analisis_lexico,String Clasificacion, JComboBox Lista, javax.swing.JLabel Cantidad)
    {   
        
        System.out.println(analisis_lexico);
        ArrayList<String> conte = appendToArray(Clasificacion, analisis_lexico);
    
      for(String a : conte){
            Lista.addItem(a);
  
    }
         
      if(Cantidad != null){
            Cantidad.setText(""+Lista.getItemCount());
        }
      
    }
    
    public Lexico() {
        initComponents();
    }
    
    public ArrayList<String> appendToArray(String clasificacion, HashMap<String, HashMap> analisis_lexico){
        ArrayList<String> array = new ArrayList<>();
        for (Map.Entry<String, HashMap> entrySet : analisis_lexico.entrySet()) {
            String key = entrySet.getKey(); //Clasificacion
            HashMap<String, Integer> value = entrySet.getValue();
           
            if (clasificacion.equals(key)){
                for (Map.Entry<String, Integer> entrySet1 : value.entrySet()) {
                    String key1 = entrySet1.getKey();

                    Integer value1 = entrySet1.getValue(); // Cuantas veces se repite
                    array.add(key1+ " = " + value1);
                    System.out.println(value1);

                }
            }
        }
        return array;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLetras = new javax.swing.JPanel();
        EtiquetaLetras = new javax.swing.JLabel();
        letras = new javax.swing.JComboBox();
        CantidadLetras = new javax.swing.JLabel();
        DiferentesLetras = new javax.swing.JLabel();
        PanelNumeros = new javax.swing.JPanel();
        EtiquetaNumeros = new javax.swing.JLabel();
        Numeros = new javax.swing.JComboBox();
        CantidadNumeros = new javax.swing.JLabel();
        DiferentesNumeros = new javax.swing.JLabel();
        PanelOperadores = new javax.swing.JPanel();
        EtiquetaOperadores = new javax.swing.JLabel();
        Operadores = new javax.swing.JComboBox();
        CantidadOperadores = new javax.swing.JLabel();
        DiferentesOperadores = new javax.swing.JLabel();
        PanelSeparadores = new javax.swing.JPanel();
        EtiquetaSeparadores = new javax.swing.JLabel();
        Separadores = new javax.swing.JComboBox();
        CantidadSeparadores = new javax.swing.JLabel();
        DiferentesSeparadores = new javax.swing.JLabel();
        PanelEspeciales = new javax.swing.JPanel();
        EtiquetaEspeciales = new javax.swing.JLabel();
        Especiales = new javax.swing.JComboBox();
        CantidadEspeciales = new javax.swing.JLabel();
        DiferentesEspeciales = new javax.swing.JLabel();
        DiferentesEspaciales2 = new javax.swing.JPanel();
        EtiquetaErrores = new javax.swing.JLabel();
        Errores = new javax.swing.JComboBox();
        CantidadErrores = new javax.swing.JLabel();
        DiferentesErrores = new javax.swing.JLabel();
        SinErrores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla = new javax.swing.JTextArea();
        CantidadEspacios = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Volver = new javax.swing.JMenuItem();
        Sintatico = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setTitle("Analisis Lexico");

        PanelLetras.setBackground(new java.awt.Color(204, 204, 204));

        EtiquetaLetras.setText("Letras:");

        DiferentesLetras.setText("Letras Diferentes:");

        javax.swing.GroupLayout PanelLetrasLayout = new javax.swing.GroupLayout(PanelLetras);
        PanelLetras.setLayout(PanelLetrasLayout);
        PanelLetrasLayout.setHorizontalGroup(
            PanelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DiferentesLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        PanelLetrasLayout.setVerticalGroup(
            PanelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrasLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(PanelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EtiquetaLetras)
                        .addComponent(letras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiferentesLetras)))
                .addContainerGap())
        );

        PanelNumeros.setBackground(new java.awt.Color(204, 204, 204));

        EtiquetaNumeros.setText("Numeros:");

        DiferentesNumeros.setText("Numeros Diferentes:");

        javax.swing.GroupLayout PanelNumerosLayout = new javax.swing.GroupLayout(PanelNumeros);
        PanelNumeros.setLayout(PanelNumerosLayout);
        PanelNumerosLayout.setHorizontalGroup(
            PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DiferentesNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        PanelNumerosLayout.setVerticalGroup(
            PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNumerosLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EtiquetaNumeros)
                        .addComponent(Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiferentesNumeros)))
                .addContainerGap())
        );

        PanelOperadores.setBackground(new java.awt.Color(204, 204, 204));

        EtiquetaOperadores.setText("Operadores:");

        DiferentesOperadores.setText("Operadores Diferentes:");

        javax.swing.GroupLayout PanelOperadoresLayout = new javax.swing.GroupLayout(PanelOperadores);
        PanelOperadores.setLayout(PanelOperadoresLayout);
        PanelOperadoresLayout.setHorizontalGroup(
            PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Operadores, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DiferentesOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        PanelOperadoresLayout.setVerticalGroup(
            PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOperadoresLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadOperadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EtiquetaOperadores)
                        .addComponent(Operadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiferentesOperadores)))
                .addContainerGap())
        );

        PanelSeparadores.setBackground(new java.awt.Color(204, 204, 204));

        EtiquetaSeparadores.setText("Separadores:");

        DiferentesSeparadores.setText("Separadores Diferentes:");

        javax.swing.GroupLayout PanelSeparadoresLayout = new javax.swing.GroupLayout(PanelSeparadores);
        PanelSeparadores.setLayout(PanelSeparadoresLayout);
        PanelSeparadoresLayout.setHorizontalGroup(
            PanelSeparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeparadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaSeparadores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separadores, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(DiferentesSeparadores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadSeparadores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        PanelSeparadoresLayout.setVerticalGroup(
            PanelSeparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeparadoresLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(PanelSeparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadSeparadores, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EtiquetaSeparadores)
                        .addComponent(Separadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiferentesSeparadores)))
                .addContainerGap())
        );

        PanelEspeciales.setBackground(new java.awt.Color(204, 204, 204));

        EtiquetaEspeciales.setText("Especiales:");

        DiferentesEspeciales.setText("Especiales Diferentes:");

        javax.swing.GroupLayout PanelEspecialesLayout = new javax.swing.GroupLayout(PanelEspeciales);
        PanelEspeciales.setLayout(PanelEspecialesLayout);
        PanelEspecialesLayout.setHorizontalGroup(
            PanelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Especiales, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(DiferentesEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PanelEspecialesLayout.setVerticalGroup(
            PanelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEspecialesLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(PanelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EtiquetaEspeciales)
                        .addComponent(Especiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiferentesEspeciales)))
                .addContainerGap())
        );

        DiferentesEspaciales2.setBackground(new java.awt.Color(204, 204, 204));

        EtiquetaErrores.setText("Errores:");

        Errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErroresActionPerformed(evt);
            }
        });

        DiferentesErrores.setText("Errores Diferentes:");

        SinErrores.setText("Sin Errores");

        javax.swing.GroupLayout DiferentesEspaciales2Layout = new javax.swing.GroupLayout(DiferentesEspaciales2);
        DiferentesEspaciales2.setLayout(DiferentesEspaciales2Layout);
        DiferentesEspaciales2Layout.setHorizontalGroup(
            DiferentesEspaciales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiferentesEspaciales2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SinErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Errores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(DiferentesErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        DiferentesEspaciales2Layout.setVerticalGroup(
            DiferentesEspaciales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiferentesEspaciales2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(DiferentesEspaciales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaErrores)
                    .addComponent(Errores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SinErrores)
                    .addComponent(DiferentesErrores)
                    .addComponent(CantidadErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Pantalla.setColumns(20);
        Pantalla.setRows(5);
        jScrollPane1.setViewportView(Pantalla);

        CantidadEspacios.setText("Espacios En Blanco:");

        jMenu1.setText("Navegacion");

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jMenu1.add(Volver);

        Sintatico.setText("Sintatico");
        Sintatico.setEnabled(false);
        Sintatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SintaticoActionPerformed(evt);
            }
        });
        jMenu1.add(Sintatico);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSeparadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEspeciales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DiferentesEspaciales2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelOperadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CantidadEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelSeparadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiferentesEspaciales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadEspacios)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        setVisible(false);                // TODO add your handling code here:
    }//GEN-LAST:event_VolverActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void ErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErroresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErroresActionPerformed

    private void SintaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SintaticoActionPerformed
        new Sintatico(texto).setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_SintaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lexico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadErrores;
    private javax.swing.JLabel CantidadEspacios;
    private javax.swing.JLabel CantidadEspeciales;
    private javax.swing.JLabel CantidadLetras;
    private javax.swing.JLabel CantidadNumeros;
    private javax.swing.JLabel CantidadOperadores;
    private javax.swing.JLabel CantidadSeparadores;
    private javax.swing.JLabel DiferentesErrores;
    private javax.swing.JPanel DiferentesEspaciales2;
    private javax.swing.JLabel DiferentesEspeciales;
    private javax.swing.JLabel DiferentesLetras;
    private javax.swing.JLabel DiferentesNumeros;
    private javax.swing.JLabel DiferentesOperadores;
    private javax.swing.JLabel DiferentesSeparadores;
    private javax.swing.JComboBox Errores;
    private javax.swing.JComboBox Especiales;
    private javax.swing.JLabel EtiquetaErrores;
    private javax.swing.JLabel EtiquetaEspeciales;
    private javax.swing.JLabel EtiquetaLetras;
    private javax.swing.JLabel EtiquetaNumeros;
    private javax.swing.JLabel EtiquetaOperadores;
    private javax.swing.JLabel EtiquetaSeparadores;
    private javax.swing.JComboBox Numeros;
    private javax.swing.JComboBox Operadores;
    private javax.swing.JPanel PanelEspeciales;
    private javax.swing.JPanel PanelLetras;
    private javax.swing.JPanel PanelNumeros;
    private javax.swing.JPanel PanelOperadores;
    private javax.swing.JPanel PanelSeparadores;
    private javax.swing.JTextArea Pantalla;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JComboBox Separadores;
    private javax.swing.JLabel SinErrores;
    private javax.swing.JMenuItem Sintatico;
    private javax.swing.JMenuItem Volver;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox letras;
    // End of variables declaration//GEN-END:variables
}
